<div align="center"> <h1>numpy</h1>
    <h2><a href="...">Richard Leibrandt</a></h2>
</div>

In [2]:
import numpy as np

# Creating Arrays - Part 1

In [3]:
a = np.array([1, 2, 3])
a[0]

np.array(  [   [1, 2],    [3, 4],    [5, 6]    ]   )

# ndim specifies the minimum number of dimensions that the resulting array should have.
# Ones will be pre-pended to the shape as needed to meet this requirement.
a = np.array([1, 2, 3, 4, 5, 6], ndmin = 1)
a = np.array([[1, 2], [3, 4], [5, 6]], ndmin = 4)

a = np.array([[1, 2, 3], [1, 2, 3]], dtype = float)

# Array Attributes

In [4]:
a = np.array([[1,2,3],[4,5,6]])
a.shape
a.reshape(3, 2)

a = np.arange(24)
a.reshape(2, 4, 3).ndim
a.reshape(2, 4, 3).shape

(2, 4, 3)

# Creating Arrays - Part 2

In [6]:
np.empty(shape=(2,2), # Shape of an empty array in int or tuple of int
         dtype = float, # Desired output data type. Optional
         order = 'C' # 'C' for C-style row-major array, 'F' for FORTRAN style column-major array
        )

np.empty([3,2], dtype = int)
np.zeros(5)
np.zeros((5,), dtype = np.int)
np.zeros((2,2))
np.ones(5)
np.ones([2, 2], dtype = int)

x = [1,2,3]
np.asarray(x)

x = [1,2,3]
np.asarray(x, dtype = float)

x = [(1,2,3), (4,5)]
np.asarray(x)

np.arange(5)
np.arange(5, dtype = float)  # dtype set
np.arange(10,20,2)  # start and stop parameters set

np.linspace(10,20,5)
np.linspace(10,20, 5, endpoint = False)
x, step = np.linspace(1,2,5, retstep = True)

np.logspace(1.0, 2.0, num = 10)  # default base is 10
np.logspace(1, 10, num = 10, base = 2)  # set base of log space to 2

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

# Basic Indexing & Slicing

In [7]:
a = np.arange(10)
s = slice(2, 7, 2)
a[s]
a[2:7:2]
a[5]  # slice single item
a[2:]  # slice items starting from index
a[2:5]  # slice items between indexes

a = np.array([[1, 2, 3], [3, 4, 5],[4,5,6]])
a[1:]  # slice items starting from index
a[..., 1]  # this returns array of items in the second column
a[1,...]  # Now we will slice all items from the second row
a[..., 1:]  # Now we will slice all items from column 1 onwards

array([[2, 3],
       [4, 5],
       [5, 6]])

# Boolean Array Indexing

In [1]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
print(x)
condition = x > 5
print(condition)
x[condition]

NameError: name 'np' is not defined

In [2]:
condition = x % 2 == 0
x[condition]

NameError: name 'x' is not defined

We are able to deal with missing values (np.nan) like this:

In [ ]:
a = np.array([np.nan, 1,2,np.nan,3,4,5])
is_not_missing = ~np.isnan(a)

a[is_not_missing]

a[~np.isnan(a)]

# Broadcasting

In [9]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b

a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
b * 2

a + b
a + b.reshape((1, -1))
a + np.concatenate([b.reshape((1, -1)),
                    b.reshape((1, -1)),
                    b.reshape((1, -1)),
                    b.reshape((1, -1))])

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

# Iterating Over Array

In [10]:
a = np.arange(0,60,5).reshape(3,4)
for x in a:
    print(x,)

for x in np.nditer(a):
    print(x,)

a = np.arange(0,60,5)
a = a.reshape(3,4)
b = a.copy(order = 'C').T
for x in np.nditer(b):
    print(x,)

# leackage of abstraction

[ 0  5 10 15]
[20 25 30 35]
[40 45 50 55]
0
5
10
15
20
25
30
35
40
45
50
55
0
5
10
15
20
25
30
35
40
45
50
55


## Iteration Order

In [11]:
a = np.arange(0,60,5).reshape(3,4)
b = a.T
c = b.copy(order = 'C')
for x in np.nditer(c):
    print(x,)

0
20
40
5
25
45
10
30
50
15
35
55


## Broadcasting Iteration

In [12]:
a = np.arange(0,60,5).reshape(3,4)
b = b.reshape((3, 4)).copy(order = 'C')
for x, y in np.nditer([a, b]):
   print("%d : %d" % (x, y),)

0 : 0
5 : 20
10 : 40
15 : 5
20 : 25
25 : 45
30 : 10
35 : 30
40 : 50
45 : 15
50 : 35
55 : 55


# Array Manipulation

In [13]:
a = np.arange(8)
a = a.reshape(4,2)
a.flat
a.flatten()

### OPTIONAL
a.flatten(order = 'F')
a.ravel()  # returns a flattened one-dimensional array. A copy is made only if needed.
a.ravel(order = 'F')
### OPTIONAL

np.transpose(a)
a.T

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.concatenate((a,b))
np.concatenate((a,b), axis = 1)
np.stack((a,b),0)
np.stack((a,b),1)
np.hstack((a,b))
np.vstack((a,b))

a = np.arange(12)
np.split(a,3)
np.split(a,[4,7])

a = np.array([[1,2,3],[4,5,6]])
a.shape
b = np.resize(a, (3,2))
b.shape

a = np.array([[1,2,3],[4,5,6]])
np.append(a, [7,8,9])
np.append(a, [[7,8,9]],axis = 0)
np.append(a, [[5,5,5],[7,8,9]],axis = 1)

array([[1, 2, 3, 5, 5, 5],
       [4, 5, 6, 7, 8, 9]])

In [14]:
# BAD:
from time import time

my_total_array = np.array([])
t0 = time()
for i in range(100):
    myarray = np.array([1,2])
    my_total_array = np.append(my_total_array, myarray)
print(time() - t0)

# GOOD:
array_list = []
t0 = time()
for i in range(100):
    myarray = np.array([1,2])
    array_list.append(myarray)
my_total_array = np.concatenate(array_list)
print(time() - t0)

0.005019664764404297
0.0008807182312011719


In [15]:
a = np.array([5,2,6,2,7,5,6,8,2,9])

# 'Return the count of repetitions of unique elements:'
u, counts = np.unique(a, return_counts = True)

# 'Unique array and Indices array:'
u, indices = np.unique(a, return_index = True)

# 'We can see each number corresponds to index in original array:'
print(a)

# 'Indices of unique array:'
u, indices = np.unique(a, return_inverse = True)

# 'Reconstruct the original array using indices:'
u[indices]

def complex_operation(x):
    return x * 2 + 3

result_a = complex_operation(a)  # what we want
result_u = complex_operation(u)
result_u[indices]  # ist gleich result_a

[5 2 6 2 7 5 6 8 2 9]


array([13,  7, 15,  7, 17, 13, 15, 19,  7, 21])